FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./

RUN \
    if [ -f yarn.lock ]; then yarn; \
    elif [ -f package-lock.json ]; then npm install; \
    elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i; \
    else echo "Lockfile not found." && yarn install; \
    fi

# Copy the rest of the application
COPY . .

# Expose the port
EXPOSE 3000

# Start the development server with hot reloading
CMD ["yarn", "dev"] 